# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaggageHandling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr_no', models.CharField(max_length=6)),
                ('quantity', models.CharField(max_length=6)),
                ('weight', models.CharField(max_length=4)),
                ('conveyor_no', models.CharField(max_length=4)),
            ],
        ),
    ]
