# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baggage_handling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baggagehandling',
            name='conveyor_no',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='baggagehandling',
            name='quantity',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='baggagehandling',
            name='weight',
            field=models.FloatField(),
        ),
    ]
