# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 17:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('worker_type', models.IntegerField(blank=True, choices=[(0, 'No Type'), (1, 'Fuelling'), (2, 'Cleaning'), (3, 'Cabin Services')], default=0)),
            ],
        ),
    ]
