# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room', models.CharField(max_length=50)),
                ('check_in', models.CharField(max_length=250)),
                ('check_out', models.CharField(max_length=250)),
                ('duration', models.CharField(max_length=250)),
                ('amt', models.CharField(max_length=250)),
            ],
        ),
    ]
