# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='check_in',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='check_out',
            field=models.DateTimeField(null=True),
        ),
    ]
