# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cargo',
            fields=[
                ('cargo_no', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('cargo_airline', models.CharField(max_length=100)),
                ('original', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('terminal', models.PositiveSmallIntegerField()),
                ('fare', models.FloatField()),
                ('weight', models.FloatField()),
               # ('scheduled_arrival', models.DateTimeField(null=True)),
                #('scheduled_departure', models.DateTimeField(null=True)),
               # ('revised_arrival', models.DateTimeField(null=True)),
                #('revised_departure', models.DateTimeField(null=True)),
                #('time_last_updated', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
