# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='scheduled_arrival',
            field=models.DateField(null='15-07-2015'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='scheduled_departure',
            field=models.DateField(null='14-07-2015'),
        ),
    ]
