# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 06:36
from __future__ import unicode_literals

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('flight_info', '0006_remove_flight_status_delayed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.IntegerField(blank=True, choices=[(0, 'Traveller'), (1, 'Employee')], max_length=1, null=True)),
                ('contact_no', models.BigIntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=accounts.models.content_file_name, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('ticket_no', models.IntegerField(blank=True, null=True)),
                ('employee_id', models.IntegerField(blank=True, null=True)),
                ('DOJ', models.DateField(blank=True, null=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('designation', models.IntegerField(blank=True, choices=[(0, 'Small'), (1, 'Medium'), (2, 'High'), (3, 'Very High')], max_length=1, null=True)),
                ('department', models.IntegerField(blank=True, choices=[(0, 'Flight/Ticketing'), (1, 'Baggage Handling'), (2, 'Cargo Handling'), (3, 'Maintenance Services'), (4, 'Parking'), (5, 'Retiring Room'), (6, 'Security'), (7, 'HR')], max_length=1, null=True)),
                ('salary', models.FloatField(blank=True, null=True)),
                ('flight_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_info.Flight')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
