# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='designation',
            field=models.IntegerField(blank=True, choices=[(0, 'Worker'), (1, 'Clerk'), (2, 'Assistant'), (3, 'Manager'), (4, 'Assistant Manager'), (5, 'General Manager')], null=True),
        ),
    ]
