# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='designation',
            field=models.IntegerField(blank=True, choices=[(0, b'Worker'), (1, b'Clerk'), (2, b'Assistant'), (3, b'Manager'), (4, b'Assistant Manager'), (5, b'General Manager')], null=True),
        ),
    ]
