# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='flight_no',
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.IntegerField(blank=True, choices=[(0, 'Flight/Ticketing'), (1, 'Baggage Handling'), (2, 'Cargo Handling'), (3, 'Maintenance Services'), (4, 'Parking'), (5, 'Retiring Room'), (6, 'Security'), (7, 'HR')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='designation',
            field=models.IntegerField(blank=True, choices=[(0, 'Small'), (1, 'Medium'), (2, 'High'), (3, 'Very High')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Traveller'), (1, 'Employee')], null=True),
        ),
    ]
