# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight_info', '0006_remove_flight_status_delayed'),
        ('accounts', '0002_auto_20170704_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='flight_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flight_info.Flight'),
        ),
    ]
