# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170704_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(0, 'No Type'), (1, 'Traveller'), (2, 'Employee')], default=0),
        ),
    ]
