# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import flight_info.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('flight_prefix', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('license_no', models.PositiveIntegerField()),
                ('no_of_aircrafts', models.PositiveIntegerField(default=0)),
                ('logo', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=flight_info.models.airline_img_path, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('info', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('crew_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('pilot', models.BooleanField(default=False)),
                ('experience', models.PositiveSmallIntegerField(default=0)),
                ('license_no', models.PositiveIntegerField()),
                ('ph_no', models.BigIntegerField()),
                ('photo', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=flight_info.models.crew_img_path, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('in_service', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_no', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('terminal', models.PositiveSmallIntegerField()),
                ('concourse', models.PositiveSmallIntegerField()),
                ('fare', models.FloatField()),
                ('total_seats', models.PositiveIntegerField()),
                ('booked_seats', models.PositiveIntegerField(default=0)),
                ('approved_plan', models.BooleanField(default=False)),
                ('operation_days', models.CharField(max_length=13)),
                ('scheduled_arrival', models.DateTimeField(null=True)),
                ('scheduled_departure', models.DateTimeField(null=True)),
                ('revised_arrival', models.DateTimeField(null=True)),
                ('revised_departure', models.DateTimeField(null=True)),
                ('time_last_updated', models.DateField(auto_now_add=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_info.Airline')),
            ],
        ),
        migrations.AddField(
            model_name='crew',
            name='flights',
            field=models.ManyToManyField(blank=True, to='flight_info.Flight'),
        ),
    ]
