# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('pilot_or_crew', models.BooleanField(default=False)),
                ('crew_id', models.IntegerField(primary_key=True, serialize=False)),
                ('experience', models.PositiveSmallIntegerField()),
                ('license', models.PositiveIntegerField()),
                ('ph_no', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_no', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('airline', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('terminal', models.PositiveSmallIntegerField()),
                ('concourse', models.PositiveSmallIntegerField()),
                ('fare', models.FloatField()),
                ('total_seats', models.PositiveIntegerField()),
                ('booked_seats', models.PositiveIntegerField()),
                ('operation_days', models.CommaSeparatedIntegerField(max_length=50)),
                ('approved_plan', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_delayed', models.BooleanField(default=False)),
                ('scheduled_arrival', models.DateTimeField()),
                ('scheduled_departure', models.DateTimeField()),
                ('revised_arrival', models.DateTimeField()),
                ('revised_departure', models.DateTimeField()),
                ('flight_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_info.Flight')),
            ],
        ),
        migrations.AddField(
            model_name='crew',
            name='flight_link',
            field=models.ManyToManyField(blank=True, to='flight_info.Flight'),
        ),
    ]
