# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='in_service',
            field=models.BooleanField(default=True),
        ),
    ]
