# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='flight_no',
        ),
        migrations.RenameField(
            model_name='crew',
            old_name='pilot_or_crew',
            new_name='pilot',
        ),
        migrations.AddField(
            model_name='flight',
            name='revised_arrival',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='revised_departure',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='scheduled_arrival',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='scheduled_departure',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='status_delayed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
