# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='info',
            field=models.TextField(default=''),
        ),
    ]
