# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_info', '0002_auto_20170623_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crew',
            old_name='flight_link',
            new_name='flights',
        ),
        migrations.RenameField(
            model_name='crew',
            old_name='license',
            new_name='license_no',
        ),
        migrations.AddField(
            model_name='flight',
            name='time_last_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='crew',
            name='experience',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flight',
            name='booked_seats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
