# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight_info', '0005_auto_20170627_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='status_delayed',
        ),
    ]
