# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import flight_info.models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_info', '0006_remove_flight_status_delayed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='crew',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crew',
            name='photo',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=flight_info.models.content_file_name, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='crew',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_info.Airline'),
        ),
    ]
