# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spots_available', models.IntegerField(default=0)),
                ('spots_occupied', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDetail',
            fields=[
                ('vehicle_no', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('vehicle_type', models.IntegerField(choices=[(2, '2-wheeler(Motorcycle/Scooter)'), (3, '3-wheeler(Auto)'), (4, '4-wheeler(Car/Bus)')])),
                ('date', models.DateField()),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
            ],
        ),
    ]
